$IPAddress = Get-NetIPAddress -AddressFamily IPv4 | Where-Object PrefixOrigin -eq "DHCP" | Select-Object IPAddress, InterfaceAlias, AddressFamily

Clear-Host
Write-Output ""
Write-Output "   #     # ####### #        #####  ####### #     # #######    ####### ### #     #   "
Write-Output "   #  #  # #       #       #     # #     # ##   ## #             #     #  ##   ##   "
Write-Output "   #  #  # #       #       #       #     # # # # # #             #     #  # # # #   "
Write-Output "   #  #  # #####   #       #       #     # #  #  # #####         #     #  #  #  #   "
Write-Output "   #  #  # #       #       #       #     # #     # #             #     #  #     #   "
Write-Output "   #  #  # #       #       #     # #     # #     # #             #     #  #     #   "
Write-Output "    ## ##  ####### #######  #####  ####### #     # #######       #    ### #     #   "
Write-Output ""
Write-Output ""
Write-Output "       PS Version: $($PSVersionTable.PSVersion.Major).$($PSVersionTable.PSVersion.Minor).$($PSVersionTable.PSVersion.Patch)"
Write-Output ""
Write-Output "       Device: $($env:COMPUTERNAME)"
Write-Output "       User: $((Get-ChildItem Env:\USERNAME).Value)"
Write-Output "       IPv4: $($IPAddress.IPAddress)"
Write-Output ""
Write-Output "       Shortcut Quick Reference"
Write-Output "          > 'onedrive' - Navigate to OneDrive directory"
Write-Output "          > 'project' - Navigate to PowerShell Projects directory"
Write-Output ""
Write-Output ""
Write-Output ""
Write-Output ""
Write-Output ""
Write-Output ""